spring:
  application:
    name: hexagonal-architecture
  datasource:
    url: jdbc:postgresql://localhost:5432/book_management
    username: postgres
    password: superpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # For development; use `validate` in production
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true

springdoc:
  swagger-ui:
    path: /api-documentation
    validatorUrl: none
    disable-swagger-default-url: true
  api-docs:
    path: /api-documentation-json

